version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "${CODE}:/var/www/html"
      - "./nginx/site.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php
    depends_on:
      - "php"
      - "mongo"
  php:
    build: ./php
    volumes:
        - "${CODE}:/var/www/html"
    links:
        - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongodb-data:/data/db"
volumes:
  mongodb-data:
